crudexample/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('salary/', views.salary),
    path('showsal/', views.showsal),
    path('editsal/<int:id>', views.editsal),
    path('updatesal/<int:id>', views.updatesal),
    # path('indexsal/', views.indexsal),
    path('indexsal1/', views.indexsal1, name='indexsal1'),
    path('deletesal/<int:id>', views.destroysal),
]

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
	eid = models.IntegerField(primary_key=True)
	ename = models.CharField(max_length=100)
	eemail = models.EmailField()
	econtact = models.CharField(max_length=10)
	class Meta:
		db_table = "employee"

	def __str__(self):
		return self.ename

class Salary(models.Model):
	id = models.IntegerField(primary_key=True)
	eid = models.ForeignKey(Employee, on_delete=models.CASCADE, unique=True)
	esalary = models.IntegerField()

	class Meta:
		db_table = "salary"

employee/forms.py
from django import forms
from employee.models import Employee, Salary


class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = "__all__"

class SalaryForm(forms.ModelForm):
	class Meta:
		model = Salary
		fields = ['esalary']

employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm,  SalaryForm
from employee.models import Employee, Salary


def emp(request):
	if request.method == 'POST':
		form = EmployeeForm(request.POST)
		if form.is_valid():
			try:
				form.save()
				return redirect('/show')
			except:
				pass
	else:
		form = EmployeeForm()
	return render(request, 'index.html', {'form':form})

# def indexsal(request):

# 	employees = Employee.objects.all()
# 	return render(request, 'indexsal.html', {'employees':employees})

def indexsal1(request):
	if request.method == 'POST':
		# nid = request.POST.get("nid")
		esalary = request.POST.get("esalary")
		salary_id = request.POST.get("empid")
		eid = Employee.objects.get(eid=salary_id)
		Salary.objects.create(esalary=esalary, id=salary_id, eid=eid)
		return redirect('/showsal')

	else:
		return render(request, 'indexsal.html', {'employees': Employee.objects.all()})


def show(request):
	employees = Employee.objects.all()
	return render(request, 'show.html', {'employees':employees})

def showsal(request):
	employees = Salary.objects.all()
	return render(request, 'showsal.html', {'employees':employees})


def edit(request, id):
	employee = Employee.objects.get(eid=id)
	return render(request, 'edit.html', {'employee':employee})

def editsal(request, id):
	employee = Salary.objects.get(id=id)
	return render(request, 'editsal.html', {'employee':employee})

def update(request, id):
	employee = Employee.objects.get(eid=id)
	form = EmployeeForm(request.POST, instance = employee)
	if form.is_valid():
		form.save()
		return redirect('/show')
	return render(request, 'edit.html', {'employee':employee})

def updatesal(request, id):
	employee = Salary.objects.get(id=id)
	form = SalaryForm(request.POST, instance = employee)
	print(request.POST, "post")
	if form.is_valid():
		form.save()
		return redirect('/showsal')
	return render(request, 'editsal.html', {'employee':employee})

def destroy(request, id):
	employee = Employee.objects.get(eid=id)
	employee.delete()
	return redirect('/show')

def salary(request):
	employees = Employee.objects.all()
	return render(request, 'salary.html', {'employees': employees, 'salary': salary})

def destroysal(request, id):
	employee = Salary.objects.get(eid=id)
	employee.delete()
	return redirect('/showsal')

employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Edit</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
	<form method="POST" class="post-form" action="/update/{{employee.eid}}">
		{% csrf_token %}
		<div class="container">
			<br>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<h3>Update details</h3>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Id:</label>
				<div class="col-sm-4">
					<input type="text" name="eid" id="id_eid" value="{{employee.eid}}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Name:</label>
				<div class="col-sm-4">
					<input type="text" name="ename" id="id_ename" value="{{employee.ename}}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Email:</label>
				<div class="col-sm-4">
					<input type="email" name="eemail" id="id_eemail" value="{{employee.eemail}}">
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Contact:</label>
				<div class="col-sm-4">
					<input type="text" name="econtact" id="id_econtact" value="{{employee.econtact}}">
				</div>
			</div>
			<div class="form-group row">
				|<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<button type="submit" class="btn btn-success">Update</button>
				</div>
			</div>
		</div>
	</form>

</body>
</html>

employee/templates/editsal.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Edit</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
	<h2>Update Salary</h2>
	<form method="POST" class="post-form" action="/updatesal/{{employee.id}}">
		{% csrf_token %}
		<div class="container">
			<br>
			<div>
				<label>Employee ID: {{employee.eid.eid}}</label>
			</div>
			<br>
			<div>
				<label>Employee Name: {{employee.eid.ename}}</label>
			</div>
			<br>
			<div>
				<label>Employee Email: {{employee.eid.eemail}}</label>
			</div>
			<br>
			<div>
				<label>Employee Contact: {{employee.eid.econtact}}</label>
			</div>
			<br>
			<div>
				<label>(Salary)Employee Id: {{employee.id}}</label>
			</div>
			<br>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Salary</label>
				<div class="col-sm-4">
					<input type="number" name="esalary" id="id_esalary" value="{{employee.esalary}}">
				</div>
			</div>
			<div class="form-group row">
				|<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<button type="submit" class="btn btn-success">Update Salary</button>
				</div>
			</div>
		</div>
	</form>

</body>
</html>

employee/templates/index.html
<!DOCTYPE html>
<html lan="en">
<head>
	<meta charset="utf-8">
	<title>Index</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>
<body>
	<form method="POST" class="post-form" action="/emp">
		{% csrf_token %}
		<div class="container">
			<br>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<h3>Enter Details</h3>
					
				</div>
				
			</div>
			<br>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Id:</label>
				<div class="col-sm-4">
					
					{{form.eid}}

				</div>
				
			</div>
			<br>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Name:</label>
				<div class="col-sm-4">
					
					{{form.ename}}

				</div>
				
			</div>
			<br>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Email:</label>
				<div class="col-sm-4">
					
					{{form.eemail}}

				</div>
				
			</div>
			<br>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Employee Contact:</label>
				<div class="col-sm-4">
					
					{{form.econtact}}

				</div>
				
			</div>
			<br>
			<br>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
				
			</div>

		</div>
	</form>

</body>
</html>

employee/templates/indexsal.html
<!DOCTYPE html>
<html>
<head>
	<title>Salary Page</title>
</head>
<body>
	<form action="{% url 'indexsal1' %}" method="post">
		{% csrf_token %}
		Employee ID: <select name="empid">
			{% for employee in employees %}
					<option value="{{employee.eid}}" selected="selected">{{employee.eid}}-{{employee.ename}}</option>
			{% endfor %}
		</select>
		Enter Salary:- <input type="number" name="esalary">
		
		<input type="submit" value="Save" />
	</form>  
</html>

employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Employee Records</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
</head>
<body>
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th class="my_tr">Employee ID</th>
				<th class="my_tr">Employee Name</th>
				<th class="my_tr">Employee Email</th>
				<th class="my_tr">Employee Contact</th>
				<th class="my_tr">Actions</th>
			</tr>
			
		</thead>
		<tbody>
			{% for employee in employees %}
			<tr>
				<td>{{employee.eid}}</td>
				<td>{{employee.ename}}</td>
				<td>{{employee.eemail}}</td>
				<td>{{employee.econtact}}</td>
				<td>
					<a href="/edit/{{employee.eid}}">
						<span class="glyphicon glyphicon-pencil">
							Edit
						</span>
					</a>
					<a href="/delete/{{employee.eid}}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
<br>
<br>
<center>
	<a href="/emp" class="btn btn-primary">Add New Record</a>
</center>
</body>
</html>

employee/templates/showsal.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Salary Records</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}">
</head>
<body>
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th class="my_tr">Employee EID</th>
				<th class="my_tr">Employee Name</th>
				<th class="my_tr">Employee Salary</th>
				<th class="my_tr">ID (Salary)</th>
				<th class="my_tr">Actions</th>
			</tr>
			
		</thead>
		<tbody>
			{% for employee in employees %}
			<tr>
				<td>{{employee.eid.eid}}</td>
				<td>{{employee.eid.ename}}</td>
				<td>{{employee.esalary}}</td>
				<td>{{employee.id}}</td>
				<td>
					<a href="/editsal/{{employee.id}}">
						<span class="glyphicon glyphicon-pencil">
							Edit
						</span>
					</a>
					<a href="/deletesal/{{employee.id}}">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
<br>
<br>
<center>
	<a href="/indexsal1/" class="btn btn-primary">Add New Record in Salary</a>
</center>
</body>
</html>